version: '3'
services:
  node:
    build: docker/node
    volumes:
      - .:/usr/src/app
    tty: true
    working_dir: /usr/src/app/react-first
    ports:
      - "3000:3000"
      - "5000:5000"
    command: yarn start
  go:
    image: 'golang:1.12'
    tty: true
    volumes:
      - ./server:/go/src
    working_dir: /go/src
    ports:
      - "8080:8080"
    expose: 
      - "8080"
    command: go run main.go