version: '3'
services:
  node:
    build: docker/node
    volumes:
      - .:/usr/src/app
    tty: true
    working_dir: /usr/src/app/react-first
    ports:
      - "3000:3000"
      - "5000:5000"
      